import Head from "next/head";
import Image from "next/image";
import { FC } from "react";
import { GrGithub } from "react-icons/gr";
import useSWR from "swr";
import styles from "../styles/Home.module.css";

interface RepoType {
  name: string;
  description: string;
  html_url: string;
}

const CardComponent: FC<RepoType> = (props) => {
  return (
    <a href={props.html_url} className={styles.card}>
      <h2>{props.name} &rarr;</h2>
      <p>{props.description}</p>
    </a>
  );
};

export default function Home() {
  const { data } = useSWR<RepoType[]>(
    "https://api.github.com/users/asurraa/repos"
  );
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>AsurRaa OSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/asurraa">AsurRaa OSS</a>
        </h1>
        <p className={styles.description}>
          Checkout our <code>OSS</code> projects
        </p>

        <div className={styles.grid}>
          {data?.map((data, index) => {
            return (
              <CardComponent
                html_url={data.html_url}
                name={data.name}
                description={data.description}
                key={index}
              />
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <GrGithub size={37} />
          </span>
          <span className={styles.logo}>
            <Image src="/asurraa.png" alt="AsurRaa" width={40} height={40} />
          </span>
        </a>
      </footer>
    </div>
  );
}
